### PR TITLE
JIT: Align func for trace JIT exit stubs

### PR DESCRIPTION
**Pull request by PeterYang12**
Fixed GH-11120

### CODE REVIEW

**Review by dstogov — APPROVED** [review]
I think, exit groups are already always aligned (because of luck).
Anyway, this won't make any harm.

**Comment by iluuu1994** [comment]
Note that the failures look legit.

**Comment by dstogov** [comment]
> Note that the failures look legit.

I see. :(
It seems like exit groups are not always aligned now.
Their alignment requires the resulting ``entry`` adjustment.

**Review by dstogov — CHANGES_REQUESTED** [review]
``entry`` have to be aligned.
Tests need to fixed.

**Comment by iluuu1994** [comment]
Oh, sorry. I didn't even realize this PR was added to the fork. I followed the link from the issue. Sorry is this was intended for personal purposes.

**Comment by dstogov** [comment]
@ iluuu1994  I also didn't notice the target :)

**Comment by PeterYang12** [comment]
> ollowed the link from the issue. Sorry is this was inte

It's my fault. This was not intended for personal purposes. I just to see the CI result if adding this alignment before I file a formal PR.
Besides, thanks too much to Dmitry and you for your observant comments.
According to the comments above, it makes sense to do it right? Let me find a proper way to do it and fix the CI tests above. I will file a PR later.
Thanks again @iluuu1994  @dstogov.

**Pull request closed without merging**
